### ISSUE TITLE
Why references?

### ISSUE THREAD

**Issue by virtualritz** [jkvargas/russimp#2]
I am just looking at the docs. LOts of types seem to use references for no apparent reason.

E.g. `russimp::face::Face` is a `Vec<&'a u32>`.

This means a 64bit pointer to a 32bit value. Or *eight* bytes wasted for every mesh index plus a runtime penalty due to the pointer deref required to get to the actual value.

Sorry if this may be a stupid question but what is the reason for this? Why not use a `Vec<u32>`?

**Comment by jkvargas** [comment]
Hey my friend. Nice to see you 
Well, the references are mainly because when working on this project I based myself on C

`bool DoTheImportThing( const char* pFile) {
  // Start the import on the given file with some example postprocessing
  // Usually - if speed is not the most important aspect for you - you'll t
  // probably to request more postprocessing than we do in this example.
  const struct aiScene* scene = aiImportFile( pFile,
    aiProcess_CalcTangentSpace       |
    aiProcess_Triangulate            |
    aiProcess_JoinIdenticalVertices  |
    aiProcess_SortByPType);

  // If the import failed, report it
  if( NULL != scene) {
    DoTheErrorLogging( aiGetErrorString());
    return false;
  }

  // Now we can access the file's contents
  DoTheSceneProcessing( scene);

  // We're done. Release all resources associated with this import
  aiReleaseImport( scene);
  return true;
}
`

so as soon as you're not using stuff anymore you should release everything with aiReleaseImport.
which is basically what is happening with this API.
Everything is going to follow the lifetime of the scene, as soon as scene gets released this piece of code will be executed:

`impl<'a> Drop for Scene<'a> {
    fn drop(&mut self) {
        unsafe {
            aiReleaseImport(self.scene);
        }
    }
}`

I am totally open to suggestion for improvement and feel free if you want to send a commit as well :)

**Comment by virtualritz** [comment]
So I understand the original data is on the other side of the FFI and you reference that?

If that were the case I would suggest to just copy the data on the Rust side and call `aiReleaseImport(self.scene)` immediately after.

The overhead of doing a few `memcpy()`s is much less than dereferencing a 64bit pointer every time you access a component of a scene.

**Comment by jkvargas** [comment]
Sounds very logical.
Will put my hands on it at the end of the day :)

**Comment by jkvargas** [comment]
I believe that this weekend I will release the changes :)

**Comment by virtualritz** [comment]
Awesome!

**Comment by jkvargas** [comment]
hey, I have updated the project.
If you have some minutes take a look and let me know what do you think. Please.
